language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"



deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: PaulineLc/TwitterBot
  bucket: twitterbots
  region: 
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: twitterbots
  key: latest.zip
  bundle_type: zip
  application: TwitterBots
  deployment_group: TwitterBots
  region: us-west-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
